version: '3.4'

services:
  rigdb:
    container_name: rigdb
    environment:
      SA_PASSWORD: "rig1234"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  portainer: 
    container_name: portainer
    restart : always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rig.api:
    container_name: rig.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rigdb
    ports:
      - "7001:80"
